version: '3.8'

services:
  go-http-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-view-info:latest
    ports:
      - "1234:8080"
    container_name: go-view-info
    restart: always
